services:
  testzone-app:
    build: .
    container_name: testzone-app
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: testzone-db
    environment:
      POSTGRES_USER: testzone
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testzone
